title: "Nishantâ€™s Tech Blog"
tagline: "Documenting my journey."
description: "Building stuff."

timezone: America/New_York
url: "https://nishantnepal.github.io"
baseurl: ""
theme: jekyll-theme-chirpy
compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
mermaid:
  enable: true
  theme: auto
github:
  username: nishantnepal
