title: "Nishantâ€™s Tech Blog"
tagline: "Documenting my journey."
description: "Building stuff."

timezone: America/New_York
url: "https://nishantnepal.github.io"
baseurl: ""
theme: jekyll-theme-chirpy
mermaid:
  enable: true
github:
  username: nishantnepal
